# Generated by Django 5.2.14 on 2026-05-25 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='activity_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.activityrecord'),
        ),
    ]
