# Generated by Django 5.2.14 on 2026-05-25 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('FUEL_COMBUSTION', 'Fuel combustion'), ('PROCESS_EMISSIONS', 'Process emissions'), ('ELECTRICITY', 'Purchased electricity'), ('BUSINESS_TRAVEL_FLIGHT', 'Business travel – flight'), ('BUSINESS_TRAVEL_HOTEL', 'Business travel – hotel'), ('BUSINESS_TRAVEL_GROUND', 'Business travel – ground transport'), ('PROCUREMENT', 'Purchased goods & services')], max_length=40)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=30)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('source_system', models.CharField(max_length=100)),
                ('source_row_id', models.CharField(blank=True, max_length=255)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for audit')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
            ],
        ),
    ]
