# Generated by Django 5.2.14 on 2026-05-25 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='ingestion.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='raw_row',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.rawrow'),
        ),
    ]
