# Generated by Django 6.0.7 on 2026-09-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionbatch',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
